### ISSUE TITLE
Allow colon in filenames

### ISSUE THREAD

**Issue by kpcyrd** [in-toto/in-toto-rs#16]
The colon symbol is currently in the set of illegal characters for file names:

https://github.com/in-toto/in-toto-rs/blob/2b9ba422fe079395cb01b8a18d5da5df0b980a2d/src/models/helpers.rs#L54-L55

This prevents in-toto from generating signatures for Arch Linux packages that have an epoch, eg `rust-1:1.56.1-3-x86_64.pkg.tar.zst`.

**Comment by SantiagoTorres** [comment]
I think we could just be less stringent here. I'll add this as an UFG

**Comment by Mo-Fatah** [comment]
I have a great interest in this project and I would like to start contributing for GSOC 2022. Can I start with this issue ?
I would also really appreciate If there is any suggestion on how to tackle the codebase. Thank you!

**Comment by adityasaky** [comment]
Oh, and UFG stands for "up for grabs". We use that label elsewhere instead of "Good First Issue", but it's GFI here.

**Comment by Mo-Fatah** [comment]
Thanks @adityasaky , I will join the slack channel to know more about the project. And yes, I will submit my proposal for https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md#add-slsa-provenance-support-to-in-toto-rs-and-rebuilderd . I am just playing around the codebase to start getting familiar with the project.

Now, I will work on this issue and see what breaks and try to fix it.

**Comment by adityasaky** [comment]
Good luck!
