### ISSUE TITLE
Metablock is not safe object

### ISSUE THREAD

**Issue by cutecutecat** [in-toto/in-toto-rs#33]
Thanks to the discussion of @Xynnn007

When he is working on verifylib, he finds that the function `load_links_for_layout` which will return a dict contains `Link` or `Layout`.
The return value may like:
```
{
      <step name> : {
        <functionary key id> : <Metablock containing a Link or Layout object>,
        ...
      }, ...
    }
```
as showed at https://github.com/in-toto/in-toto/blob/f6a91bfbff29c98f58e05d9346c8245b6ef9a6a6/in_toto/verifylib.py#L94.

In Rust version, the ideal implement of this function may like:
```rust
fn load_links_for_layout(
    layout: &LayoutMetadata,
    link_dir: &str,
) -> Result<HashMap<String, HashMap<KeyId, Metablock<Json, dyn Metadata>>>>
```
However, as the `Metablock` and `Metadata` is **not safe object**, he can only write the function as:
```Rust
fn load_links_for_layout(
    layout: &LayoutMetadata,
    link_dir: &str,
) -> Result<HashMap<String, (HashMap<KeyId, Metablock<Json, LinkMetadata>>, HashMap<KeyId, Metablock<Json, LayoutMetadata>>)>>
```

From my view, there will be some way to refactor the `MetaData` and `Metablock` to make them object safe. The source of unsafe comes from Trait `PartialEq + Serialize + DeserializeOwned`. We can move methods about Serialize and there traits outside of `Metablock`.

I would like to do this refactor if everyone think it is necessary, maybe on November after my job at hand is done.

**Comment by SantiagoTorres** [comment]
SGTM!

**Comment by Xynnn007** [comment]
May be handled by https://github.com/in-toto/in-toto-rs/pull/34
Hi @cutecutecat , I have learned a lot from your thinking ways in your newest PR. Would you help me to review this PR?

**Comment by Xynnn007** [comment]
Hi, this issue can now be closed

**Comment by cutecutecat** [comment]
Thanks to @Xynnn007 , we can step to next target now.
