### ISSUE TITLE
Inconsistent logic in `calculate_key_id` with python version

### ISSUE THREAD

**Issue by Xynnn007** [in-toto/in-toto-rs#37]
For both versions, a key id is calculated by sha256sum a canonicalize JSON object, after formatted like
```json
{
    "keyid_hash_algorithms":["sha256","sha512"],
    "keytype":"rsa",
    "keyval":{"public":"<BASE64-ENCODED-DERBYTES>"},
    "scheme":"rsassa-pss-sha256"
}
```

The difference is `"<BASE64-ENCODED-DERBYTES>"`:
* Python version: A pem string without public key header and footer, e.g.

```plaintext
MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAxPX3kFs/z645x4UOC3KF
Y3V80YQtKrp6YS3qU+Jlvx/XzK53lb4sCDRU9jqBBx3We45TmFUibroMd8tQXCUS
e8gYCBUBqBmmz0dEHJYbW0tYF7IoapMIxhRYn76YqNdl1JoRTcmzIaOJ7QrHxQrS
GpivvTm6kQ9WLeApG1GLYJ3C3Wl4bnsI1bKSv55Zi45/JawHzTzYUAIXX9qCd3Io
HzDucz9IAj9Ookw0va/q9FjoPGrRB80IReVxLVnbo6pYJfu/O37jvEobHFa8ckHd
YxUIg8wvkIOy1O3M74lBDm6CVI0ZO25xPlDB/4nHAE1PbA3aF3lw8JGuxLDsetxm
fzgAleVt4vXLQiCrZaLf+0cM97JcT7wdHcbIvRLsij9LNP+2tWZgeZ/hIAOEdaDq
cYANPDIAxfTvbe9I0sXrCtrLer1SS7GqUmdFCdkdun8erXdNF0ls9Rp4cbYhjdf3
yMxdI/24LUOOQ71cHW3ITIDImm6I8KmrXFM2NewTARKfAgMBAAE=
```

And in the json there will be multiple `\n`s

* Rust version: A base64-encoded der bytes string, e.g.
```plaintext
MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAzgLBsMFSgwBiWTBmVsyW5KbJwLFSodAzdUhU2Bq6SdRz_W6UOBGdojZXibxupjRtAaEQW_eXDe-1CbKg6ENZGt2D9HGFCQZgQS8ONgNDQGiNxgApMA0T21AaUhru0vEofzdN1DfEF4CAGv5AkcgKsalhTyONervFIjFEdXGelFZ7dVMV3Pp5WkZPG0jFQWjnmDZhUrtSxEtqbVghc3kKAUj9Ll_3jyi2wS92Z1j5ueN8X62hWX2xBqQ6nViOMzdujkoiYCRSwuMLRqzW2CbTL8hF1-S5KWKFzxl5sCVfpPe7V5HkgEHjwCILXTbCn2fCMKlaSbJ_MG2lW7qSY2RowVXWkp1wDrsJ6Ii9f2dErv9vJeOVZeO9DsooQ5EuzLCfQLEU5mn7ul7bU7rFsb8JxYOeudkNBatnNCgVMAkmDPiNA7E33bmL5ARRwU0iZicsqLQR32pmwdap8PjofxqQk7Gtvz_iYzaLrZv33cFWWTsEOqK1gKqigSqgW9T26wO9AgMBAAE=
```
There is not any `\n`s

Because of the difference, the resulted keyid will be different, which will cause incompatible issue when a python-created layout and public key needs to be created by rust. It will result wrong KeyId.

**Comment by adityasaky** [comment]
Thanks for flagging this, @Xynnn007. Can you submit a patch, do you think?

**Comment by Xynnn007** [comment]
> Thanks for flagging this, @Xynnn007. Can you submit a patch, do you think?

Sure, here are the two PRs to fix both the CI error and this.
https://github.com/in-toto/in-toto-rs/pull/39
https://github.com/in-toto/in-toto-rs/pull/38
