### ISSUE TITLE
Inconsistent format of publickey with python version

### ISSUE THREAD

**Issue by Xynnn007** [in-toto/in-toto-rs#40]
In Rust In-toto, a serialized public key's `keyval` do not have a member `private`, e.g.
```json
{
    "keyid": "2f89b9272acfc8f4a0a0f094d789fdb0ba798b0fe41f2f5f417c12f0085ff498",
    "keyid_hash_algorithms": [
        "sha256",
        "sha512"
    ],
    "keytype": "rsa",
    "keyval": {
        "public": "-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAzgLBsMFSgwBiWTBmVsyW\n5KbJwLFSodAzdUhU2Bq6SdRz/W6UOBGdojZXibxupjRtAaEQW/eXDe+1CbKg6ENZ\nGt2D9HGFCQZgQS8ONgNDQGiNxgApMA0T21AaUhru0vEofzdN1DfEF4CAGv5AkcgK\nsalhTyONervFIjFEdXGelFZ7dVMV3Pp5WkZPG0jFQWjnmDZhUrtSxEtqbVghc3kK\nAUj9Ll/3jyi2wS92Z1j5ueN8X62hWX2xBqQ6nViOMzdujkoiYCRSwuMLRqzW2CbT\nL8hF1+S5KWKFzxl5sCVfpPe7V5HkgEHjwCILXTbCn2fCMKlaSbJ/MG2lW7qSY2Ro\nwVXWkp1wDrsJ6Ii9f2dErv9vJeOVZeO9DsooQ5EuzLCfQLEU5mn7ul7bU7rFsb8J\nxYOeudkNBatnNCgVMAkmDPiNA7E33bmL5ARRwU0iZicsqLQR32pmwdap8PjofxqQ\nk7Gtvz/iYzaLrZv33cFWWTsEOqK1gKqigSqgW9T26wO9AgMBAAE=\n-----END PUBLIC KEY-----"
    },
    "scheme": "rsassa-pss-sha256"
}
```

But in both python and golang version, it will have one, e.g.
```json
{
    "keyid": "2f89b9272acfc8f4a0a0f094d789fdb0ba798b0fe41f2f5f417c12f0085ff498",
    "keyid_hash_algorithms": [
        "sha256",
        "sha512"
    ],
    "keytype": "rsa",
    "keyval": {
        "private": "",
        "public": "-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAzgLBsMFSgwBiWTBmVsyW\n5KbJwLFSodAzdUhU2Bq6SdRz/W6UOBGdojZXibxupjRtAaEQW/eXDe+1CbKg6ENZ\nGt2D9HGFCQZgQS8ONgNDQGiNxgApMA0T21AaUhru0vEofzdN1DfEF4CAGv5AkcgK\nsalhTyONervFIjFEdXGelFZ7dVMV3Pp5WkZPG0jFQWjnmDZhUrtSxEtqbVghc3kK\nAUj9Ll/3jyi2wS92Z1j5ueN8X62hWX2xBqQ6nViOMzdujkoiYCRSwuMLRqzW2CbT\nL8hF1+S5KWKFzxl5sCVfpPe7V5HkgEHjwCILXTbCn2fCMKlaSbJ/MG2lW7qSY2Ro\nwVXWkp1wDrsJ6Ii9f2dErv9vJeOVZeO9DsooQ5EuzLCfQLEU5mn7ul7bU7rFsb8J\nxYOeudkNBatnNCgVMAkmDPiNA7E33bmL5ARRwU0iZicsqLQR32pmwdap8PjofxqQ\nk7Gtvz/iYzaLrZv33cFWWTsEOqK1gKqigSqgW9T26wO9AgMBAAE=\n-----END PUBLIC KEY-----"
    },
    "scheme": "rsassa-pss-sha256"
}
```

This problem will cause the generated `keyid` different between `in-toto-rs` and other two implements.

**Comment by adityasaky** [comment]
The Python implementation will tolerate the field but will omit it. The Go implementation will include it but that's technically against a spec and should be fixed. The rust implementation described here is correct IMO. cc @lukpueh

**Comment by adityasaky** [comment]
We've discussed this in https://github.com/in-toto/in-toto/issues/186 as well.

**Comment by Xynnn007** [comment]
> We've discussed this in [in-toto/in-toto#186](https://github.com/in-toto/in-toto/issues/186) as well.

Thanks for the link! The problem this issue pointed to occurs when use this demo https://github.com/in-toto/demo to generate a layout. The layout will have its functionary public keys format containing a `private` but empty field. There are two different behaviors:
* When calculating the `keyid`, the `private` field will not be the part of input of the hash function. 
* When exporting the `layout` string (serialize), the outputted `layout.json` will have a `private` field with `""` value

Sorry for the misleading, but the two different behaviors are what I wanted to point out
