### ISSUE TITLE
Add support for ecdsa keys

### ISSUE THREAD

**Issue by danbev** [in-toto/in-toto-rs#43]
This issue suggests adding support for `ecdsa` keys.

The motivation for this is to be able to use keys that are generated by cosign. Also, `in-toto` command line tools are able to accept [ecdsa keys](https://github.com/in-toto/in-toto/pull/520) which might also be a motivating factor.

I'd be happy to take a stab at this, just wanted to see if there are any objections/issues first.

**Comment by adityasaky** [comment]
No objections, a PR would be great! Thanks!
